import { Card } from '../../../components/ui/Card';
import { Badge } from '../../../components/ui/Badge';
import type { SculptureAnalysis } from '../../../types/sculpture';

interface AnalysisPanelProps {
  analysis: SculptureAnalysis;
}

export function AnalysisPanel({ analysis }: AnalysisPanelProps) {
  return (
    <Card className="p-6 h-full flex flex-col">
      <div className="flex items-start justify-between mb-6">
        <div>
          <h3 className="text-xl font-semibold text-surface-900 dark:text-white">Analysis Summary</h3>
          <p className="text-sm text-surface-500 dark:text-surface-400 mt-1">Generated by AI Creative Director</p>
        </div>
        <Badge variant="primary" className="text-sm px-3 py-1">
          {analysis.period || "Unknown Period"}
        </Badge>
      </div>

      <div className="prose prose-surface dark:prose-invert max-w-none flex-1">
        <p className="text-surface-700 dark:text-surface-300 leading-relaxed">
          {analysis.summary || analysis.composition_notes || "Analysis complete. No additional summary provided."}
        </p>
      </div>

      <div className="mt-8 space-y-6">
        <div>
          <h4 className="text-sm font-semibold text-surface-900 dark:text-white uppercase tracking-wider mb-3">Detected Traits</h4>
          <ul className="space-y-2">
            {(analysis.materials || analysis.style_traits || []).map(material => (
              <li key={material} className="flex items-center gap-2 text-surface-700 dark:text-surface-300">
                <span className="w-1.5 h-1.5 rounded-full bg-secondary-500 shrink-0" />
                <span>{material}</span>
              </li>
            ))}
          </ul>
        </div>

        <div>
          <div className="flex justify-between items-center mb-2">
            <h4 className="text-sm font-semibold text-surface-900 dark:text-white uppercase tracking-wider">AI Confidence</h4>
            <span className="text-sm font-medium text-primary-600 dark:text-primary-400">
              {(analysis.confidence * 100).toFixed(1)}%
            </span>
          </div>
          <div className="w-full h-2 bg-surface-100 dark:bg-surface-800 rounded-full overflow-hidden">
            <div 
              className="h-full bg-gradient-to-r from-primary-500 to-accent-500 rounded-full transition-all duration-1000 ease-out"
              style={{ width: `${analysis.confidence * 100}%` }}
            />
          </div>
        </div>
      </div>
    </Card>
  );
}
