"""Add AI Models

Revision ID: 094327909e15
Revises: add_ideas_table
Create Date: 2026-06-16 00:00:43.600408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '094327909e15'
down_revision: Union[str, None] = 'add_ideas_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.create_table('ancient_art_chunks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ancient_art_chunks_id'), 'ancient_art_chunks', ['id'], unique=False)
    op.create_table('creative_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creative_runs_id'), 'creative_runs', ['id'], unique=False)
    op.create_index(op.f('ix_creative_runs_project_id'), 'creative_runs', ['project_id'], unique=False)
    op.create_table('critiques',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('idea_id', sa.String(), nullable=False),
    sa.Column('persona', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('weaknesses', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_critiques_id'), 'critiques', ['id'], unique=False)
    op.create_index(op.f('ix_critiques_idea_id'), 'critiques', ['idea_id'], unique=False)
    op.create_table('style_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('traits', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_style_profiles_id'), 'style_profiles', ['id'], unique=False)
    op.drop_constraint('fk_ideas_project_id', 'ideas', type_='foreignkey')
    op.create_foreign_key(None, 'ideas', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ideas', type_='foreignkey')
    op.create_foreign_key('fk_ideas_project_id', 'ideas', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_style_profiles_id'), table_name='style_profiles')
    op.drop_table('style_profiles')
    op.drop_index(op.f('ix_critiques_idea_id'), table_name='critiques')
    op.drop_index(op.f('ix_critiques_id'), table_name='critiques')
    op.drop_table('critiques')
    op.drop_index(op.f('ix_creative_runs_project_id'), table_name='creative_runs')
    op.drop_index(op.f('ix_creative_runs_id'), table_name='creative_runs')
    op.drop_table('creative_runs')
    op.drop_index(op.f('ix_ancient_art_chunks_id'), table_name='ancient_art_chunks')
    op.drop_table('ancient_art_chunks')
    # ### end Alembic commands ###
