"""Stage 9 Evolution Engine

Revision ID: e59fb48bd6f4
Revises: 2f4faca6e6d3
Create Date: 2026-06-16 17:41:15.260888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e59fb48bd6f4'
down_revision: Union[str, None] = '2f4faca6e6d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sculpture_kb_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('period', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('material', sa.String(), nullable=True),
    sa.Column('iconography', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('prompt_name', sa.String(), nullable=False),
    sa.Column('prompt_version', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('latency', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('workflow_run_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_outcomes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('idea_id', sa.String(), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('feedback', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refined_outputs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('idea_id', sa.String(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('refined_text', sa.Text(), nullable=False),
    sa.Column('style_alignment_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refined_outputs_idea_id'), 'refined_outputs', ['idea_id'], unique=False)
    op.add_column('analysis_results', sa.Column('iconography', sa.JSON(), nullable=True))
    op.add_column('analysis_results', sa.Column('motifs', sa.JSON(), nullable=True))
    op.add_column('analysis_results', sa.Column('composition_notes', sa.String(), nullable=True))
    op.add_column('analysis_results', sa.Column('style_traits', sa.JSON(), nullable=True))
    op.add_column('analysis_results', sa.Column('raw_payload', sa.JSON(), nullable=True))
    op.drop_column('analysis_results', 'summary')
    op.drop_column('analysis_results', 'tags')
    op.drop_index(op.f('ancient_art_chunks_embedding_idx'), table_name='ancient_art_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.add_column('ideas', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    op.add_column('projects', sa.Column('learned_preferences', sa.JSON(), nullable=True))
    op.drop_index(op.f('style_profiles_embedding_idx'), table_name='style_profiles', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.add_column('workflow_runs', sa.Column('reasoning_trace', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_runs', 'reasoning_trace')
    op.create_index(op.f('style_profiles_embedding_idx'), 'style_profiles', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_column('projects', 'learned_preferences')
    op.drop_column('ideas', 'embedding')
    op.create_index(op.f('ancient_art_chunks_embedding_idx'), 'ancient_art_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.add_column('analysis_results', sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('analysis_results', sa.Column('summary', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('analysis_results', 'raw_payload')
    op.drop_column('analysis_results', 'style_traits')
    op.drop_column('analysis_results', 'composition_notes')
    op.drop_column('analysis_results', 'motifs')
    op.drop_column('analysis_results', 'iconography')
    op.drop_index(op.f('ix_refined_outputs_idea_id'), table_name='refined_outputs')
    op.drop_table('refined_outputs')
    op.drop_table('project_outcomes')
    op.drop_table('prompt_runs')
    op.drop_table('sculpture_kb_entries')
    # ### end Alembic commands ###
